usdot-fhwa-stol/cdasim

.circleci/config.yml
Dockerfile
docker/checkout.sh

Make circle CI use the dev images so that it is always building off the develop branch of carma-base. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/723
Better CI
Running CI on this PR

Make CI use dev images

---

co-simulation tool/docker/ns3-docker/README.md

Fix the path error in the run.sh
In Step 4 modify run.sh, the path to the LD_LIBRARY_PATH is not correct.
Change .../fed/bin/... to .../bin/fed/... in the LD_LIBRARY_PATH.
The docker image of ns-3 integration can not be run. Co-simulation tool can not start the ns-3 simulator correctly.

Fix the path errors in the run.sh.

---

carla-carma-integration/carla_carma_bridge/CMakeLists.txt
carla-carma-integration/carla_carma_bridge/src/carla_carma_bridge/carla_to_autoware_vehicle_status
carla-carma-integration/carla_carma_bridge/src/carla_carma_bridge/carla_to_carma_vehicle_status
carla-carma-integration/carla_carma_bridge/src/carla_carma_bridge/carma_to_carla_ackermann_cmd

Fix CARLA CARMA bridge scripts

---

co-simulation tool/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaIdTransformer.java
co-simulation tool/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaInstance.java
co-simulation tool/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaInstanceManager.java
co-simulation tool/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaMessageAmbassador.java
co-simulation tool/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaV2xMessage.java
co-simulation tool/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaV2xMessageReceiver.java

Initial implementation of CARMA Message Ambassador Updates to satisfy XIL-104. Currently adds:
1. CARMA Instance Management
2. Socket interface to send/receive data from CARMA Platform
3. Message parsing for outbound messages from CARMA Platform
4. Message buffering and lookup to persist data sent/received by CARMA Platform
Pending further development:
1. Outbound (messages to CARMA Platform) binary message encoding in accordance with RSU specification 4.0.
2. CARMA Host ID <--> MOSAIC Actor ID transforms. Pending updates to CARLA-MOSAIC Integration.
This change set will allow CARMA Platform instances to interface with NS-3 as the MOSAIC side of the interface. The CARMA Platform will use the `ns3_adapter` driver to communicate data with these updates in the CARMA Message Ambassador in …

Initial commit of update CARMA Message Ambassador

---

co-simulation/NOTICE-THIRD-PARTY.md
co-simulation/fed/mosaic-carma/pom.xml
co-simulation/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaInstanceManager.java
co-simulation/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaMessageAmbassador.java
co-simulation/fed/mosaic-infrastructure/pom.xml
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceManager.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassador.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassadorTest.java
co-simulation/lib/mosaic-carma-utils/pom.xml
co-simulation/lib/mosaic-carma-utils/src/main/java/gov/dot/fhwa/saxton/CarmaV2xMessage.java
co-simulation/lib/mosaic-carma-utils/src/main/java/gov/dot/fhwa/saxton/CarmaV2xMessageReceiver.java
co-simulation/pom.xml

Refactored existing logic into new maven module to re-use for infrastructure ambassador
Migrating the v2x-message reception logic into a shared library so it can be easily incorporated into the infrastructure ambassador without code duplication.
Hasn't been tested yet, original module wasn't unit tested so I'll write some tonight but wanted to get this review out before COB.
- [] My change requires a change to the documentation.

Migrate logic for v2x messaging from platform to infrastructure

---

co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassador.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureTimeMessage.java

Updated infrastructure time message to use millisecond timestep instead of nanosecond time step since that is what V2X-Hub and CARMA-Streets expect and we do not do any nanosecond level logic on infrastructure.
Fix bugs related to V2X-Hub/CARMA Streets Time Synchronization
- [ x] Defect fix (non-breaking change that fixes an issue)
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.

Fixed Infrastructure Time message to use timestep in milliseconds

---

co-simulation/lib/mosaic-carma-utils/src/main/java/gov/dot/fhwa/saxton/CarmaV2xMessage.java
co-simulation/lib/mosaic-carma-utils/src/main/java/gov/dot/fhwa/saxton/CarmaV2xMessageReceiver.java
co-simulation/lib/mosaic-carma-utils/src/test/java/gov/dot/fhwa/saxton/CarmaV2xMessageTest.java

Added logic to skip over any junk bytes at the start of the UDP packet to only process it from where the AMF message actually starts.
New unit test added to evaluate logic and passes

Add logic to find start of AMF message

---

co-simulation/bundle/src/assembly/resources/scenarios/Town04/sumo/Town04.rou.xml
co-simulation/bundle/src/assembly/resources/scenarios/Town04_test/sumo/Town04.rou.xml

For the K900 test plan, it doesn't include the test of the scenario vehicle (SUMO generated vehicles). This PR is to remove  SUMO vehicles but left only one with depart time far away from the beginning which is necessary for SUMO to run. 

Removed SUMO vehicle in Town04 and Town04_test scenario

---

co-simulation/bridge/carla_integration/bridge_helper.py
co-simulation/bridge/carla_integration/synchronization.py

The current CDASim can synchronize vehicle positions and orientations between Carla and SUMO simulations. However, there's an issue with the correct synchronization of SUMO IDs and Carla role names. This PR aims to address and fix this problem.

Set sumo vehicle id to corresponding carla vehicle role name

---

co-simulation/bundle/src/assembly/resources/scenarios/Town04/sumo/Town04.sumocfg
co-simulation/bundle/src/assembly/resources/scenarios/Town04/sumo/gui.settings.xml

Set Delay to 1000 ms per second to startup SUMO running at approximately real-time to avoid time sync issues with simulation and infrastructure
Due to this issue (https://github.com/usdot-fhwa-OPS/V2X-Hub/issues/540) the current time synchronization between infrastructure (V2X-Hub) and CDASim is non-time regulating, meaning Infrastructure does not currently have a way of notifying CDASim when it is ready for time to advance in simulation. Due to this, is simulation is running faster than real time, Infrastructure can begin to fall behind. To avoid this, this PR adds a GUI settings file to the SUMO GUI, which is used to play/pause/step through the simulation. In this settings file, we can configure the delay, a sumo GUI feature that controls how long, if at all, between time steps SUMO …

Added configuration files for sumo GUI settings

---

co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassador.java

InfrastructureMessageAmbassador throws nullpointer exception when infrastructure registration message includes no sensor registrations. This PR addresses that and addresses some sonar code smells about logger calls
Fix null pointer

Fix null pointer when infrastructure registration includes no sensor registrations

---

scenario-runner/README.md
scenario-runner/my_scenario.py
scenario-runner/my_scenario.xml
scenario-runner/requirements.txt

This PR adds example CARLA ScenarioRunner configurations that we can use for integration testing with CARMA. These files are intended to be example references rather than concrete test scenarios. More work is necessary to integrate this functionality with CDASim
Closes #160
[CDAR-334](https://usdot-carma.atlassian.net/browse/CDAR-334)
ScenarioRunner provides an easier way to define and run integration test scenarios within CARLA. Incorporating this functionality into CDASim will greatly help with automating integration tests.
Manually verified the scenario runs as intended.
[CARMA Contributing Guide](Contributing.md) 
[CDAR-334]: https://usdot-carma.atlassian.net/browse/CDAR-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add example ScenarioRunner configurations

---

co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstance.java

Sensor list is initialized as an empty array so an exception is not thrown if there is no sensor configuration.
[CDAR-427](https://usdot-carma.atlassian.net/browse/CDAR-427)
If a sensor configuration file is not available, registration throws a NullPointerException exception causing CDASim to crash. This is not the desired behavior, since there may be times when a sensor config does not exist.
The solution is to initialize the sensors list as an empty list.
local integration tested
[CARMA Contributing Guide](Contributing.md) 
[CDAR-427]: https://usdot-carma.atlassian.net/browse/CDAR-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

initialize sensors list

---

co-simulation/NOTICE-THIRD-PARTY.md
co-simulation/bundle/src/assembly/resources/scenarios/Town04/carla/carla_config.json
co-simulation/bundle/src/assembly/resources/scenarios/Town04_test/carla/carla_config.json
co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassador.java
co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/carlaconnect/CarlaXmlRpcClient.java
co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/config/CarlaConfiguration.java
co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassadorTest.java
co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/carlaconnect/CarlaXmlRpcClientTest.java
co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/config/CarlaConfigurationTest.java
co-simulation/fed/mosaic-carla/src/test/resources/carla_config.json
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassador.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceManagerTest.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceTest.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassadorTest.java
co-simulation/lib/mosaic-interactions/src/main/java/org/eclipse/mosaic/interactions/detector/DetectorRegistration.java
co-simulation/lib/mosaic-interactions/src/test/java/org/eclipse/mosaic/interactions/detector/DetectedObjectInteractionTest.java
co-simulation/lib/mosaic-interactions/src/test/java/org/eclipse/mosaic/interactions/detector/DetectorRegistrationTest.java
co-simulation/lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/detector/DetectedObject.java
co-simulation/lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/detector/DetectedObjectTest.java

Add logic to CARLA Ambassador to use XMLRPC Client to dynamically create sensor and retrieve detections. More specifically: the CARLA Ambassador will now create a CARLA XML RPC Client on startup. Its configuration parameters (constructor arguments) will be loaded from the carla_config.json configuration file for the CARLA Ambassador. This is currently limited to **carlaCDASimAdapterUrl** which tells the XMLRPC client where the XMLRPC server is hosted.
Next the CARLA Ambassador now listens for **Detector Registration Interactions** which are triggered by the Infrastructure Ambassador in response to infrastructure registration attempts that include sensors. When receiving a **Detector Registration Interaction**, the CARLA Ambassador will tell the CARLA XML RPC Client to make a …

Update CARLA Ambassador to use XMLRPC Client

---

co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassadorTest.java
co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/carlaconnect/CarlaXmlRpcClientTest.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceManagerTest.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceTest.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassadorTest.java
co-simulation/lib/mosaic-interactions/src/test/java/org/eclipse/mosaic/interactions/detector/DetectedObjectInteractionTest.java
co-simulation/lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/detector/DetectedObject.java
co-simulation/lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/detector/DetectedObjectTest.java

Fix Detected Object class to include timestamp
[CDAR-446
](https://usdot-carma.atlassian.net/browse/CDAR-446)
Unit testing

Fix Detected Object class

---

scenario-runner/examples/trb_2024.xml
scenario-runner/scenarios/trb_2024.py

This PR adds the left-turn scenario for TRB.
Replaces this PR: https://github.com/usdot-fhwa-stol/cdasim/pull/180
Closes #179 
Progresses [CDAR-399](https://usdot-carma.atlassian.net/browse/CDAR-399)
Closes [CDAR-518](https://usdot-carma.atlassian.net/browse/CDAR-518)
We want to persist the TRB 2024 scenario configuration so it can be easily used by others.
Manually tested in simulation
[CDAR-399]: https://usdot-carma.atlassian.net/browse/CDAR-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDAR-518]: https://usdot-carma.atlassian.net/browse/CDAR-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add TRB 2024 OpenScenario left turn scenario

---

co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassador.java
co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/carlaconnect/CarlaXmlRpcClient.java
co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/config/CarlaConfiguration.java
co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassadorTest.java
co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/carlaconnect/CarlaXmlRpcClientTest.java
co-simulation/fed/mosaic-carla/src/test/resources/carla_config.json

Add functionality to CARLA Ambassador to, on initialization, attempt to connect to CARLA CDASim Adapter, with some retry limit. This avoids deployment timing issues that occasionally cause the CARLA Ambassador to drop Sensor Registrations if the CARLA CDA Sim Adapter is not up yet.
**NOTE** This PR requires closing of (https://github.com/usdot-fhwa-stol/carla-sensor-lib/pull/2)
[CDAR-667
](https://usdot-carma.atlassian.net/browse/CDAR-667)
Improve robustness of deployment by reattempting failing connection on startup, that could fail purely due to CDASim deployment timing issues.
Sim Computer

Add logic to connect and retry connection for CARLA Ambassador

---

.github/workflows/ci.yml
co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassador.java
co-simulation/pom.xml

This PR updates incoming CARLA detections, which have Carla time stamps, to have cdasim time stamps since all components in this system use cdasim time. This fix is necessary because prior to establishing connection to cdasim, carla spins for some time, creating a random static time offset between carla game-time and cda sim simulation time. 
**NOTE**: This PR also includes necessary fixes to use java 17 for sonar scanner CI process
CDAR-756
Gives detection data a simulation time step that should be accurate to sim time.
CDASim deployment

CDAR-756: Carla Ambassador correct detection timestamp

---

co-simulation/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaMessageAmbassador.java

This is a duplicate of PR #198 meant to include these changes in our release candidate branch
CDAR-764
Fix time sync message updates for CARMA Platform
CDASim deployment

Fix time sync message updates

---

co-simulation/bundle/src/assembly/resources/scenarios/Town04/ns3/ns3_federate_config.xml

Change default communication model for Town04
CDAR-833
CV2X-Model needs investigation due to introduced communication latency
CDASim Deployment

CDAR-833: Set default Comm Type to DSRC

---

co-simulation/fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java

Previous PR here https://github.com/usdot-fhwa-stol/cdasim/pull/205 merged a log statement line that the time sync script relies on (https://github.com/usdot-fhwa-stol/carma-analytics-fotda/pull/43).
- However, it had a typo, which this PR fixes.
- This PR also removes the debug log requirement for this line change because one simulation run log from _this same class_ could easily be 500MB. Time sync script is working too much to parse every single line and is having adverse effect. 
Since the line is just a log statement, it is safe to leave it in there without DEBUG option and its size goes up to 500kb or so
vs
https://github.com/usdot-fhwa-stol/cdasim/issues/209
https://usdot-carma.atlassian.net/browse/CDAR-662 
https://usdot-carma.atlassian.net/browse/CDAR-774
VRU verification testing …

Remove debug flag requirement for time sync script log for sumo

---

co-simulation/bundle/src/assembly/resources/scenarios/Town04/scenario_config.json
co-simulation/legal/templates/leidos-license-header-2024.txt
co-simulation/lib/mosaic-geomath/pom.xml
co-simulation/lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/transform/Proj4Projection.java
co-simulation/lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/transform/Proj4ProjectionTest.java
co-simulation/pom.xml
co-simulation/rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/config/CProjection.java
co-simulation/rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java
co-simulation/rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/config/CScenario.java

This PR adds pose transformation in mosaic using Proj. During testing it was found that the map transform calculated by mosaic on the data subscribed to from Traci, does not have geodetic coordinates that match the values calculated by carma-platform. 
In order to fix this, the transform library in mosaic was extended to accept another parameter for the georeference string which can be used to calculate the geodetic coordinates like it is being calculated in carma-platform and sumo natively (Using proj).
The added georeference field is an optional argument to the mosaic scenario_configuration.
https://usdot-carma.atlassian.net/browse/CXC-91
Integration tested on xil_carma_cloud scenario on develop and vru scenario on carma-system-4.5.0.

Cxc 91 update pose transform lib
