usdot-fhwa-stol/cdasim

Dockerfile
carla_ackermann_control/package.xml
carla_ackermann_control_wrapper/package.xml
docker/build-image.sh

PR for updating package.xml files.
Changed package.xml files for every package in this repository to format 3.
https://github.com/usdot-fhwa-stol/carma-platform/issues/763
This change is required to move carma to newer software.
This has been tested by successfully building this repository.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md)

Updated package.xml files

---

.circleci/config.yml
Dockerfile
docker/checkout.sh

Updates develop to match the 3.4.3 release
Develop and master are kept in sync
Local docker build

Feature/sync 3.4.3

---

docker/build-image.sh

Add missing fix that should have been in
https://github.com/usdot-fhwa-stol/carma-simulation/pull/12

Fix build image .sh for dev and candidate images

---

docker-compose.yml

Correct wrong image name

---

carla-carma-integration/carla_carma_bridge/src/carla_carma_bridge/carla_to_carma_external_objects

CARLA ros bridge could not provide the velocity twist of external objects. Adding method to calculate that based on position and time differences

Adding method to calculate velocity twist for external object function.

---

carla-carma-integration/Dockerfile
carla-carma-integration/README.md

Added environment setting in carla-carma-integration README.md file

---

carla-carma-integration/carla-carma-agent/agent/bridge.launch
carla-carma-integration/carla_carma_bridge/config/parameters.yaml
carla-carma-integration/carla_carma_bridge/config/parameters.yml
carla-carma-integration/carla_carma_bridge/src/carla_carma_bridge/carma_carla_guidance
carla-carma-integration/carla_carma_bridge/src/carla_carma_bridge/carma_carla_plugins
carla-carma-integration/carla_carma_bridge/src/carla_carma_bridge/carma_carla_route

Update CARMA CARLA guidance state machine

---

docker/install.sh

Added wget "https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/CARLA_0.9.10.tar.gz" line to download the CARKA_0.9.10.tar.gz file which required during build runtime.

install.sh: wget CARLA_0.9.10.tar.gz

---

.github/workflows/docker.yml
.github/workflows/dockerhub.yml

Add GitHub workflows

---

docker/install.sh

install.sh: conditionally download CARLA tarball
#105

install.sh: conditionally download CARLA tarball

---

co-simulation/bridge/carla_integration/sumo_simulation.py
co-simulation/bridge/carla_integration/synchronization.py
co-simulation/bridge/carla_mosaic_bridge.py
co-simulation/bundle/src/assembly/resources/etc/runtime.json
co-simulation/fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java
co-simulation/fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/traci/TraciClient.java
co-simulation/fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/traci/commands/TraciSetOrder.java
co-simulation/fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/traci/constants/CommandSimulationControl.java

SUMO multi client feature for EVC integration

---

.github/workflows/runtest.yml
co-simulation/pom.xml

This PR is to setup sonar cloud to run the C++ tests and publish the sonar cloud reports on sonarcloud.io

Add CI for Sonar

---

.github/workflows/runtest.yml
Dockerfile
co-simulation/pom.xml
co-simulation/test/ci/ci-image-mvn-sumo/Dockerfile
docker/install.sh

Upgrade to java 11 since mosias is compatible with java 8/11/17. Update also resolved issues related to using maven sonar scanner plugin which can not be executed in jre 8 and requires at least jre 11.
https://github.com/usdot-fhwa-stol/devops/issues/78
Fix UI and update java
CI/CD
- [x ] Defect fix (non-breaking change that fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

Updated Java version to 11 for maven sonar scanner plugin

---

evc-sumo/Dockerfile
evc-sumo/docker/build-image.sh
evc-sumo/docker/checkout.sh
evc-sumo/docker/entrypoint.sh
evc-sumo/docker/env.sh
evc-sumo/docker/get-component-version.sh
evc-sumo/docker/get-image-name.sh
evc-sumo/docker/get-repo-name.sh
evc-sumo/docker/get-system-version.sh
evc-sumo/docker/install.sh
evc-sumo/docker/token.txt

upload evc essential files
Implement EVC docker
To build EVC docker image, user need to replace the content of token.txt file with their own github token

EVC dockerization

---

co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstance.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceManager.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassador.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureTimeInterface.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureTimeMessage.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureTimeInterfaceTest.java

implementation of time sync and unit testing
The implementation of  InfrastructureTimeInterface class, which includes encoding time message and updating to registered instances.
Unit testing for InfrastructureTimeInterface

updates for timesync and test

---

co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassador.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassadorTest.java

Correct wrong MOSAIC header

---

evc-sumo/src/evc_sumo_bridge.py
evc-sumo/src/sumo_connector.py

add traic ip argument for evc-sumo connection

---

co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstance.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceManager.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureMessageAmbassador.java
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureRegistrationMessage.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceManagerTest.java
co-simulation/fed/mosaic-infrastructure/src/test/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureRegistrationReceiverTest.java

GeoPoint to CartesianPoint for infrastructure

---

co-simulation/bridge/carla_integration/sumo_simulation.py
co-simulation/bridge/carla_integration/synchronization.py
co-simulation/fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/util/MosaicConformVehicleIdTransformer.java

Fix CARLA generated vehicle ID mismatch issue in MOSAIC

---

co-simulation/bundle/src/assembly/resources/etc/logback.xml

Updated logback settings to include fully qualified class name and line number to log statements (https://logback.qos.ch/manual/layouts.html)
Improve usability of log files
Locally integration tests

Add fully qualified class name and line number for logging.

---

.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/dockerhub.yml

Update github action workflows to avoid duplicate or unnecessary actions. Docker build should only be executed on Pull Requests that are open. It builds the docker images to confirm the docker build process still works. Dockerhub build should only be run on master,develop and release branches for creating appropriate docker images and pushing them to our repository.
Remove unnecessary money/time used for unnecessary github actions
NA

Update github action workflows to avoid duplicate actions on PRs

---

scenario-runner/examples/sensorlib_lidar_field_of_view.xml
scenario-runner/scenarios/sensorlib_lidar_field_of_view.py

This PR adds a new ScenarioRunner scenario to facilitate with `sensorlib` field of view integration testing.
Closes #173 
Progresses [CDAR-368](https://usdot-carma.atlassian.net/browse/CDAR-368)
Manually verified
[CDAR-368]: https://usdot-carma.atlassian.net/browse/CDAR-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ScenarioRunner scenario for `sensorlib` integration test

---

co-simulation/bundle/src/assembly/resources/scenarios/Town04/sumo/Town04.sumocfg

remove error line

---

co-simulation/bundle/src/assembly/resources/etc/runtime.json
co-simulation/bundle/src/assembly/resources/scenarios/Town04/carla/carla_config.json

Add subscription for `DetectorRegistration` interactions to facilitate creation of CARLA Sensors.
Update CARLA CDA Sim Adapter host to match carma-config:xil-cloud (https://github.com/usdot-fhwa-stol/carma-config/blob/develop/xil_cloud/docker-compose.yml) 172.2.0.5:8000
[CDAR-517
](https://usdot-carma.atlassian.net/browse/CDAR-517)
Fix CARLA Sensor detection pipeline
Tested on Sim computers

CARLA Ambassador configuration fixes

---

co-simulation/bundle/src/assembly/resources/etc/runtime.json
co-simulation/fed/mosaic-infrastructure/src/main/java/org/eclipse/mosaic/fed/infrastructure/ambassador/InfrastructureInstanceManager.java

add new infrastructure ambassador config and logging  
CDAR-517

add  new log and config

---

co-simulation/bundle/src/assembly/resources/scenarios/Town04/sumo/Town04.rou.xml

Remove unnecessary sumo heavy vehicle from scenario
Locally Integration testing in Adams CDASim setup

Remove unnecessary SUMO vehicles

---

co-simulation/fed/mosaic-carla/src/main/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassador.java
co-simulation/fed/mosaic-carla/src/test/java/org/eclipse/mosaic/fed/carla/ambassador/CarlaAmbassadorTest.java

Remove redundant requests to XMLRPC CARLA CDA Sim adapter server. Also removed redundant calls to requestNextTime
[CDDAR-732
](https://usdot-carma.atlassian.net/browse/CDAR-732)
Improve performance and clean up logs
Tested in CDASim deployment

CDAR-732: Remove redundant requests

---

co-simulation/fed/mosaic-carma/src/main/java/org/eclipse/mosaic/fed/carma/ambassador/CarmaMessageAmbassador.java

CARMA Ambassador was sending timestep updates 100 ms ahead of time. This is because the CARMA Ambassador was using the value for the next time step requested instead of the value of the current time step for time sync messages.
[CDAR-764
](https://usdot-carma.atlassian.net/browse/CDAR-764)
Fix CARMA Time sync
CDASim Deployment

Fix time sync message updates

---

docker/install_dependencies.sh

Fixes error while building docker image caused by carla resources being moved to a different location.
CARLA install URL is updated to point to new location for resource.
https://github.com/usdot-fhwa-stol/cdasim/issues/201

update carla install url: develop

---

.github/workflows/ci.yml
.github/workflows/dockerhub.yml

Fix CI workflows for release and remove lavida references

---

docker/checkout.sh

Fix checkout versions to 4.5.0

---

co-simulation/bundle/src/assembly/resources/scenarios/Town04_carma_messenger/carma-messenger/carma-messenger_config.json
co-simulation/fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassador.java

added missing folder

---

co-simulation/bundle/src/assembly/resources/scenarios/Town05/sumo/Town05.rou.xml
co-simulation/tools/geneate_background_traffic.sh

Creating relevant scenario, routing, sumo files for background traffic for Town 05. 
Possible options:
1. https://sumo.dlr.de/docs/Tools/Trip.html  to generate random route files given input parameters
2. https://sumo.dlr.de/docs/od2trips.html  (origin destination) allows you to configure origin and destination as well as intermediate edges to use.
3. https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#incomplete_routes_trips_and_flows similar to od2trips but allows for definition of traffic flows (multiple vehicles that follow an origin/destination route). 
In this PR:
1. Option 1 has been selected and  background traffic route file for Town05 has been generated  using sumo tools **randomTrips.py**.
2. A bash script genrate_random_traffic.sh has been …

TT 113-Create-SUMO-background-traffic
